apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: myapp-service
  namespace: argocd

spec:
  project: default
  source:
    path: dev
    repoURL: https://github.com/nikolamar/argocd-service.git
    targetRevision: HEAD
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
