version: "3"

networks:
  my-network:
    name: my-network
    driver: bridge

services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
      target: deps
    command: npm run start
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    networks:
      - my-network
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  nodejs-volume:
    name: nodejs-volume
