apiVersion: apps/v1
kind: Deployment

# deploy
metadata:
  name: myapp-service

spec:
  # replicas
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  # upgrade pod strategy
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  # pod template
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          imagePullPolicy: Always
          image: nikolamar/svc-nodejs:latest # use your image
          ports:
            - containerPort: 3000
